/**
 * Every event type the SDK can produce.
 * Extend this union when adding new event types — do not use raw strings.
 */
export type EventType =
  | 'page_view'
  | 'scroll_depth'
  | 'time_on_page'
  | 'click'
  | 'form_submit'
  | 'media_play'
  | 'media_pause'
  | 'media_seek'
  | 'media_ended'
  | 'media_progress'
  | 'media_error'
  | 'custom';

/**
 * Arbitrary properties attached to an event by the caller.
 * Values must be primitives — the ingest API rejects nested objects.
 */
export type EventProperties = Record<string, string | number | boolean | null>;

/**
 * A fully-formed event ready to be queued and sent.
 * Produced by buildEvent(). Never mutated after creation.
 */
export interface TrackingEvent {
  // ── Identity ───────────────────────────────────────────────────────────────
  /** Unique ID — generated by the SDK, used for deduplication at ingest */
  eventId: string;

  /** Identifies which site this event belongs to */
  siteToken: string;

  /** What kind of event this is */
  eventType: EventType;

  // ── Timing ─────────────────────────────────────────────────────────────────
  /** When the event occurred — client clock, Unix ms */
  clientTimestamp: number;

  // ── Page context ───────────────────────────────────────────────────────────
  /** Full URL of the page at the time of the event */
  url: string;

  /** Document referrer — empty string if direct or unavailable */
  referrer: string;

  // ── Session ────────────────────────────────────────────────────────────────
  /** Groups all events from the same continuous visit */
  sessionId: string;

  // ── Device ─────────────────────────────────────────────────────────────────
  /** Derived from user agent — raw UA string is never stored */
  deviceType: 'desktop' | 'mobile' | 'tablet' | 'unknown';

  /** Physical screen width in logical pixels */
  screenWidth: number;

  /** Browser viewport width in logical pixels */
  viewportWidth: number;

  /** Browser language preference — e.g. 'en-US' */
  language: string;

  // ── SDK metadata ───────────────────────────────────────────────────────────
  /** Which SDK version produced this event */
  sdkVersion: string;

  // ── Optional payload ───────────────────────────────────────────────────────
  /** Event-specific data — scroll milestone, click target, etc. */
  properties?: EventProperties;
}

/**
 * Interface every media adapter must implement.
 * Allows the core SDK to treat all adapters identically.
 */
export interface MediaAdapterInterface {
  readonly name: string;
  attach(): void;
  detach(): void;
}
